development:
  host: localhost
  port: 27017
  database: thenonsequitur_dev
  logfile: development.log
    
production:
  host: localhost
  port: 27017
  database: thenonsequitur_prod
  logfile: production.log
    
environment: development